import { getAccount, getAccounts, getCampaign, getSearchTerms, getConversionActions, getAlerts, getMetaAdsets, getMetaAds } from './data.js';

const sessionStore = new Map();
const fm = (a,c) => `${c === 'GBP' ? '£' : c === 'USD' ? '$' : c+' '}${Number(a).toFixed(a % 1 === 0 ? 0 : 2)}`;
const fu = (iso,p='API') => !iso ? `Live ${p}` : `${new Date(iso).toISOString().replace('T',' ').slice(0,16)} UTC`;
const kb = (r) => ({ inline_keyboard:r }); const bt=(t,d)=>({text:t,callback_data:d});
const pi=(p)=>p==='Google Ads'?'🔎':p==='Meta Ads'?'📘':'📊';
const cl=(c)=> (c.conversions||0)>=10 && (c.cpa||0)>0 && c.cpa<=25 ? '🟢 strong' : (c.conversions||0)>=3 ? '🟡 mixed' : '🔴 watch';
const pd=(v,w)=>{const t=String(v??''); return t.length>=w?t.slice(0,w):t+' '.repeat(w-t.length)}; const cp=(t,m)=>t.length<=m?t:`${t.slice(0,m-1)}…`;
function gs(id){let s=sessionStore.get(id); if(!s){s={screen:'picker',accountId:null,campaignId:null,campaignsView:'cards',filter:'all'};sessionStore.set(id,s);} return s;}
function picker(chatId){const s=gs(chatId), items=getAccounts(s.filter).slice(0,20), gc=getAccounts('google').length, mc=getAccounts('meta').length, title=s.filter==='google'?'🔎 Google Ads Navigator':s.filter==='meta'?'📘 Meta Ads Navigator':'✨ Ads Navigator'; return {text:[title,'','Choose an account to inspect.','Read only mode is on.','',`Google: ${gc} | Meta: ${mc}`,`Showing: ${items.length} accounts`].join('\n'), reply_markup: kb([[bt('All','filter:all'),bt('Google','filter:google'),bt('Meta','filter:meta')], ...items.map((a,i)=>[bt(`${i+1}. ${pi(a.platform)} ${cp(a.businessName||a.name,18)} | ${cp(a.name,18)}`,`pick:${a.id}`)])])};}
function account(accountId){const a=getAccount(accountId); if(!a) return picker(0); return {text:[`${pi(a.platform)} ${a.businessName||a.name}`,`${a.name}`,`${a.platform} | ID: ${a.id}`,'',`💰 Spend: ${fm(a.summary.spend,a.currency)}`,`👆 Clicks: ${a.summary.clicks}`,`🎯 Conversions: ${a.summary.conversions}`,`CPA: ${fm(a.summary.cpa,a.currency)}`,`📈 CTR: ${a.summary.ctr}%`,'',`🟢 Active campaigns: ${a.summary.activeCampaigns}`,`⏸️ Paused campaigns: ${a.summary.pausedCampaigns}`,'',`Updated: ${fu(a.lastUpdated,a.platform)}`].join('\n'), reply_markup: kb([[bt('📋 Campaigns',`screen:campaigns:${a.id}`),bt('🎯 Alerts',`alerts:${a.id}`)],[bt('⚙️ Conversions',`convs:${a.id}`),bt('🔄 Refresh',`screen:account:${a.id}`)],[bt('🏠 Home','screen:picker')]])};}
function campCards(a,cs){return [`📋 ${a.businessName||a.name}`,`${a.name}`,`${a.platform} campaigns | Last 30 days`,'View: Cards','',...cs.map((c,i)=>`${i+1}. ${c.name}\n${cl(c)} | Spend ${fm(c.spend,a.currency)} | Conv ${c.conversions} | CPA ${fm(c.cpa,a.currency)}`),'',`Updated: ${fu(a.lastUpdated,a.platform)}`].join('\n');}
function campTable(a,cs){const lines=[`📊 ${a.businessName||a.name}`,`${a.name}`,`${a.platform} campaigns | Table`,'','```',`${pd('#',2)} ${pd('Campaign',22)} ${pd('Spend',7)} ${pd('Conv',5)} ${pd('CPA',7)} ${pd('Flag',6)}`]; cs.forEach((c,i)=>lines.push(`${pd(i+1,2)} ${pd(cp(c.name,22),22)} ${pd(fm(c.spend,a.currency),7)} ${pd(c.conversions,5)} ${pd(fm(c.cpa,a.currency),7)} ${pd(cl(c).split(' ')[0],6)}`)); lines.push('```','',`Updated: ${fu(a.lastUpdated,a.platform)}`); return lines.join('\n');}
function campaigns(chatId,accountId){const s=gs(chatId), a=getAccount(accountId); if(!a) return picker(chatId); const cs=(a.campaigns||[]).slice(0,5), text=s.campaignsView==='table'?campTable(a,cs):campCards(a,cs); return {text, parse_mode:s.campaignsView==='table'?'Markdown':undefined, reply_markup:kb([cs.map((c,i)=>bt(String(i+1),`camp:${a.id}:${c.id}`)),[bt(s.campaignsView==='table'?'🧾 Cards':'📊 Table',`toggle:campaigns:${a.id}`),bt('🔄 Refresh',`screen:campaigns:${a.id}`)],[bt('◀️ Back',`screen:account:${a.id}`),bt('🏠 Home','screen:picker')]])};}
function terms(accountId,campaignId){const a=getAccount(accountId), c=getCampaign(accountId,campaignId), ts=getSearchTerms(accountId,campaignId).slice(0,8); if(!a||!c) return account(accountId); if(a.platform!=='Google Ads') return {text:['🔎 Search Terms','','Search terms are available only for Google Ads right now.','',`Campaign: ${c.name}`].join('\n'), reply_markup:kb([[bt('◀️ Back to campaign',`camp:${a.id}:${c.id}`)],[bt('🏠 Home','screen:picker')]])}; const lines=['🔎 Search Terms',c.name,'','```',`${pd('#',2)} ${pd('Term',26)} ${pd('Spend',7)} ${pd('Clk',4)} ${pd('Conv',5)}`]; (ts.length?ts:[{term:'No search term rows found.',spend:'',clicks:'',conversions:''}]).forEach((t,i)=>lines.push(`${pd(ts.length?i+1:'',2)} ${pd(cp(t.term,26),26)} ${pd(t.spend!==''?fm(t.spend,a.currency):'',7)} ${pd(t.clicks,4)} ${pd(t.conversions,5)}`)); lines.push('```','',`Updated: ${fu(a.lastUpdated,a.platform)}`); return {text:lines.join('\n'), parse_mode:'Markdown', reply_markup:kb([[bt('🔄 Refresh',`terms:${a.id}:${c.id}`)],[bt('◀️ Campaign',`camp:${a.id}:${c.id}`),bt('📋 Campaigns',`screen:campaigns:${a.id}`)],[bt('🏠 Home','screen:picker')]])};}
function convs(accountId){const a=getAccount(accountId); if(!a) return picker(0); if(a.platform!=='Google Ads') return {text:['⚙️ Conversion Actions','','Detailed conversion actions are available only for Google Ads right now.'].join('\n'), reply_markup:kb([[bt('◀️ Back',`screen:account:${a.id}`)],[bt('🏠 Home','screen:picker')]])}; const cs=getConversionActions(accountId).slice(0,12), lines=['⚙️ Conversion Actions',`${a.businessName||a.name}`,'','```',`${pd('P',2)} ${pd('Type',10)} ${pd('Category',14)} Name`]; cs.forEach((c)=>lines.push(`${pd(c.primary?'Y':'N',2)} ${pd(cp(c.type,10),10)} ${pd(cp(c.category,14),14)} ${cp(c.name,28)}`)); lines.push('```','',`Updated: ${fu(a.lastUpdated,a.platform)}`); return {text:lines.join('\n'), parse_mode:'Markdown', reply_markup:kb([[bt('🔄 Refresh',`convs:${a.id}`)],[bt('◀️ Back',`screen:account:${a.id}`),bt('🏠 Home','screen:picker')]])};}
function alerts(accountId){const a=getAccount(accountId); if(!a) return picker(0); const as=getAlerts(accountId), icon=(s)=>s==='high'?'🔴':s==='medium'?'🟡':'🔵'; return {text:['🎯 Alerts',`${a.businessName||a.name}`,'',...(as.length?as.map((x,i)=>`${i+1}. ${icon(x.severity)} ${x.text}`):['No major alerts found right now.']),'',`Updated: ${fu(a.lastUpdated,a.platform)}`].join('\n'), reply_markup:kb([[bt('🔄 Refresh',`alerts:${a.id}`)],[bt('◀️ Back',`screen:account:${a.id}`),bt('🏠 Home','screen:picker')]])};}
function metaAdsets(accountId,campaignId){const a=getAccount(accountId), c=getCampaign(accountId,campaignId), sets=getMetaAdsets(accountId,campaignId).slice(0,8); if(!a||!c) return account(accountId); const lines=['🧩 Ad Sets', c.name,'','```',`${pd('#',2)} ${pd('Ad Set',24)} ${pd('Spend',7)} ${pd('Conv',5)} ${pd('CPA',7)}`]; (sets.length?sets:[{name:'No ad sets found',spend:'',conversions:'',cpa:''}]).forEach((s,i)=>lines.push(`${pd(sets.length?i+1:'',2)} ${pd(cp(s.name,24),24)} ${pd(s.spend!==''?fm(s.spend,a.currency):'',7)} ${pd(s.conversions,5)} ${pd(s.cpa!==''?fm(s.cpa,a.currency):'',7)}`)); lines.push('```','',`Updated: ${fu(a.lastUpdated,a.platform)}`); return {text:lines.join('\n'), parse_mode:'Markdown', reply_markup:kb([[bt('📣 Ads',`mads:${a.id}:${c.id}`),bt('🔄 Refresh',`madsets:${a.id}:${c.id}`)],[bt('◀️ Campaign',`camp:${a.id}:${c.id}`),bt('🏠 Home','screen:picker')]])};}
function metaAds(accountId,campaignId){const a=getAccount(accountId), c=getCampaign(accountId,campaignId), ads=getMetaAds(accountId,campaignId).slice(0,8); if(!a||!c) return account(accountId); const lines=['📣 Ads', c.name,'','```',`${pd('#',2)} ${pd('Ad',24)} ${pd('Spend',7)} ${pd('Conv',5)} ${pd('CPA',7)}`]; (ads.length?ads:[{name:'No ads found',spend:'',conversions:'',cpa:''}]).forEach((s,i)=>lines.push(`${pd(ads.length?i+1:'',2)} ${pd(cp(s.name,24),24)} ${pd(s.spend!==''?fm(s.spend,a.currency):'',7)} ${pd(s.conversions,5)} ${pd(s.cpa!==''?fm(s.cpa,a.currency):'',7)}`)); lines.push('```','',`Updated: ${fu(a.lastUpdated,a.platform)}`); return {text:lines.join('\n'), parse_mode:'Markdown', reply_markup:kb([[bt('🧩 Ad Sets',`madsets:${a.id}:${c.id}`),bt('🔄 Refresh',`mads:${a.id}:${c.id}`)],[bt('◀️ Campaign',`camp:${a.id}:${c.id}`),bt('🏠 Home','screen:picker')]])};}
function campaign(accountId,campaignId){const a=getAccount(accountId), c=getCampaign(accountId,campaignId); if(!a||!c) return account(accountId); const metaRow = a.platform==='Meta Ads' ? [bt('🧩 Ad Sets',`madsets:${a.id}:${c.id}`), bt('📣 Ads',`mads:${a.id}:${c.id}`)] : [bt('🔎 Search Terms',`terms:${a.id}:${c.id}`), bt('🔄 Refresh',`camp:${a.id}:${c.id}`)]; return {text:[`🎯 ${c.name}`,`${a.businessName||a.name}`,`${a.platform} | ${a.id}`,'',`Status: ${c.status}`,`Type: ${c.type}`,`Bidding: ${c.bidding}`,'',`💰 Spend: ${fm(c.spend,a.currency)}`,`👆 Clicks: ${c.clicks}`,`🎯 Conversions: ${c.conversions}`,`CPA: ${fm(c.cpa,a.currency)}`,`CTR: ${c.ctr}%`,`Avg CPC: ${fm(c.avgCpc,a.currency)}`,`Daily budget: ${fm(c.budgetDaily,a.currency)}`,'',`Assessment: ${cl(c)}`,`Updated: ${fu(a.lastUpdated,a.platform)}`].join('\n'), reply_markup:kb([metaRow,[bt('📋 Campaigns',`screen:campaigns:${a.id}`),bt('◀️ Account',`screen:account:${a.id}`)],[bt('🏠 Home','screen:picker')]])};}
export function renderScreen(chatId){const s=gs(chatId); if(s.screen==='account'&&s.accountId) return account(s.accountId); if(s.screen==='campaigns'&&s.accountId) return campaigns(chatId,s.accountId); if(s.screen==='campaign'&&s.accountId&&s.campaignId) return campaign(s.accountId,s.campaignId); if(s.screen==='terms'&&s.accountId&&s.campaignId) return terms(s.accountId,s.campaignId); if(s.screen==='convs'&&s.accountId) return convs(s.accountId); if(s.screen==='alerts'&&s.accountId) return alerts(s.accountId); if(s.screen==='madsets'&&s.accountId&&s.campaignId) return metaAdsets(s.accountId,s.campaignId); if(s.screen==='mads'&&s.accountId&&s.campaignId) return metaAds(s.accountId,s.campaignId); return picker(chatId);}
export function openAds(chatId,filter='all'){const s=gs(chatId); s.screen='picker'; s.accountId=null; s.campaignId=null; s.campaignsView='cards'; s.filter=filter; return renderScreen(chatId);}
export function handleCallback(chatId,d){const s=gs(chatId); if(d==='screen:picker'){s.screen='picker'; s.accountId=null; s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('filter:')){s.filter=d.slice(7); s.screen='picker'; s.accountId=null; s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('pick:')){s.screen='account'; s.accountId=d.slice(5); s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('screen:account:')){s.screen='account'; s.accountId=d.slice(15); s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('screen:campaigns:')){s.screen='campaigns'; s.accountId=d.slice(17); s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('toggle:campaigns:')){s.screen='campaigns'; s.accountId=d.slice(17); s.campaignsView=s.campaignsView==='table'?'cards':'table'; return renderScreen(chatId);} if(d.startsWith('terms:')||d.startsWith('camp:')||d.startsWith('madsets:')||d.startsWith('mads:')){const prefix=d.startsWith('terms:')?'terms:':d.startsWith('camp:')?'camp:':d.startsWith('madsets:')?'madsets:':'mads:'; const rest=d.slice(prefix.length); const i=rest.lastIndexOf(':'); s.screen=prefix==='camp:'?'campaign':prefix.replace(':',''); s.accountId=rest.slice(0,i); s.campaignId=rest.slice(i+1); return renderScreen(chatId);} if(d.startsWith('convs:')){s.screen='convs'; s.accountId=d.slice(6); s.campaignId=null; return renderScreen(chatId);} if(d.startsWith('alerts:')){s.screen='alerts'; s.accountId=d.slice(7); s.campaignId=null; return renderScreen(chatId);} return renderScreen(chatId);}
export function resetSessions(){sessionStore.clear();}
